Bug/sms format
coachmehealth/sms-care-portal-front-end pull request #18
Opened 2021-05-26 16:42 UTC by g-vega-cl

## Purpose  
- Add ability to indent
-Copy/Pasting text keeps the original formatting

## Changes and Additions  		 
-  
- In `SMSTitle.tsx` the function `formatMessageNewLine()` allows us to add `<divs>` where there are newlines so the formatting is preserved. Also a few style changes were made.
- `SMSTitle.test.ts` tests the `formatMessageNewLine ` function.
- `IPatientRecords.ts` now holds the interfaces for `PatientRecords.tsx
-  Add absolute import paths. (changes in `.eslintrc` and `package.json`)
-  Removed "use-strict" from a few files as per ESlint recommendation (the use-strict is not necessary in modules)

## Open Project Tickets

-[CSV parsing is broken in some instances; messages received from clients are being parsed into the incorrect columns w/in CSV](https://trello.com/c/vg6quwJu/74-csv-parsing-is-broken-in-some-instances-messages-received-from-clients-are-being-parsed-into-the-incorrect-columns-w-in-csv)

## Tested
- Branch is up to date to Master Branch
- Ran `yarn lint` before MR
- Ran `yarn test` before MR
- Application runs without crashes (`yarn start`)

Proof of fix (MacOS)
![Screen Shot 2021-05-26 at 11 25 30](https://user-images.githubusercontent.com/13635035/119699026-68ff0200-be17-11eb-9a0a-4f906208a155.png)

2021-06-02 16:16 UTC, rweald requested changes
Whoa, this looks like now it maybe contains a ton of different stuff, and also a merge commit from master -> branch. Which commits make the actual changes related to just the SMS formatting bug fix? 

Cesar Vega: Everything before June 1st has to do with the SMS formatting. (before the `Feature/logout button (#19) `commit. 
The Feature/logout button (#19) merge/commit includes the logout button and the inactivity logout.

2021-06-02 16:16 UTC, rweald commented on config/env.js
> -"use strict";
I'd appreciate in the future if we can not include this type of refactor in existing PRs. Makes it much harder to go through the actual intended change when it also includes somewhat unrelated changes to a ton of files.

2021-06-02 16:17 UTC, rweald commented on src/components/SMSTile/SMSTile.tsx
> +  return message.split("\n").map((i, key) => {
I'm not sure we need to actually include a `div` to make the whitespace work? Would a single div be sufficient with the necessary CSS tweaks to honor newlines? Assuming the string contains the necessary whitespace characters already.

2021-06-02 17:18 UTC, g-vega-cl commented on config/env.js
> -"use strict";
Deal, thank you for letting me know.

2021-06-02 18:07 UTC, g-vega-cl commented on src/components/SMSTile/SMSTile.tsx
> +  return message.split("\n").map((i, key) => {
The string does contain the whitespace characters already. 
Example of how the data works in Mongo:
<img width="859" alt="Screen Shot 2021-06-02 at 12 39 02" src="https://user-images.githubusercontent.com/13635035/120527093-8f84e600-c39f-11eb-9144-dcc42a70bca0.png">

2021-06-02 18:08 UTC, g-vega-cl commented on src/components/SMSTile/SMSTile.tsx
> +  return message.split("\n").map((i, key) => {
Also, you were right! I deleted `formatMessageNewLine` and just added `white-space: pre-wrap` to the css.

2021-06-25 16:53 UTC, rweald commented on src/components/SMSTile.tsx
> +            style={{ padding: "20px", height: "75px" }}
This wasn't you, but I think it's hilarious they used a styled component, but then still did inline styles 🤦

2021-06-25 16:53 UTC, rweald approved these changes

2021-06-25 17:12 UTC, closed without merging