Adrian docker
coachmehealth/sms-care-portal-front-end pull request #3
Opened 2021-02-15 01:06 UTC by mufasubhai

Appears to be working for frontend alone. Dockerfile for backend is in process as well, although having trouble getting the two to communicate. Will follow up with respect to this via slack.

2021-02-15 18:15 UTC, rweald requested changes
We will want / need to add a `.dockerignore` to this repo now as well. No reason to waste time copying over things like `node_modules` when building containers locally. Not the end of the world in production, but worth adding before we merge this code.

2021-02-15 18:15 UTC, rweald commented on Dockerfile
> +# runs both node server.js and node build/start.js
Do we need to be running the `build/start.js` script? If the assets themselves have already been built / compiled during the docker container build process, then we should be able to just serve those static assets, no? 

If we want to run the docker container using a different setup / mode for development, we can always pass in a command at runtime.

2021-02-15 18:15 UTC, rweald commented on package.json
> +    "start": "node scripts/start.js && node server.js",
Similar to above question. Seems like this might be conflating how we want to run things in development mode vs in production.

2021-02-15 18:15 UTC, rweald commented on .gitignore
> +2# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
We should remove this errant character from the ignore file.

2021-02-15 18:15 UTC, rweald commented on Dockerfile
> +RUN yarn install
I should have really included this in my example Dockerfile, but if we wanted to be diligent in product we'd do this `yarn install` with the `--frozen-lockfile` to ensure there are no dependency version differences between what we've been testing on staging + locally and what ends up running in production.

2021-02-15 18:19 UTC, rweald commented on Dockerfile
> +RUN set -a && . /app/.aptible.env && \
Were you able to get this to run locally without a `.aptible.env` file on your local computer? I think we might need to add a note to the README about ensuring you have at least a blank version of that file present?

2021-02-15 18:36 UTC, mufasubhai commented on package.json
> +    "start": "node scripts/start.js && node server.js",
For the above question, I meant to type "node scripts/start.js" referring to line 73 here. 

However, I think you are right that I"m conflating how we want to run things in development mode vs. production. In the dockerfile should we only start the express static asset server and then if developing run the start script from within the container?

2021-02-15 18:36 UTC, mufasubhai commented on .gitignore
> +2# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
good catch.

2021-02-15 18:39 UTC, mufasubhai commented on Dockerfile
> +RUN yarn install
nice. I've added to both.

2021-02-15 18:51 UTC, mufasubhai commented on Dockerfile
> +RUN set -a && . /app/.aptible.env && \
This didn't raise any issues for me running locally. Doesn't line 17 take care of the posibility of .aptible.env not being present? If I'm being honest I'm confused by line 19, though.

2021-02-15 21:59 UTC, rweald commented on Dockerfile
> +RUN set -a && . /app/.aptible.env && \
Ohh you are right, silly me not noticing the touch on the preceding line. TBH line 19 is a bit of a "hack" to give us access to environment variables during the docker build process. Basically it's a bit of bash to that you can essentially source all the variables defined in `.aptible.env` into the running shell, a lot like what some people do with `.env` files. Main reason we want this is so that we can compile values directly into the static assets, like the URI for the backend, etc.

2021-02-15 22:00 UTC, rweald commented on package.json
> +    "start": "node scripts/start.js && node server.js",
Yeah I'd say we have the Dockerfile default to only running static express server. If we want to run the actual build server dynamically for local development that's super easy by just passing in that command to docker cli when you run the container, or even just including it as the custom command in the docker-compose file since that's also only for development.

2021-02-16 18:03 UTC, rweald commented
Going to close this one as I took the main patch and the necessary changes and submitted a new PR #5

2021-02-16 18:03 UTC, closed without merging