Fix coach dropdown
coachmehealth/sms-care-portal-front-end pull request #31
Opened 2021-07-09 18:03 UTC by g-vega-cl

Purpose:
- When adding a new patient through the UI, replace usage of fancy auto complete text input for coach name with a old fashioned select input, which is more accessible and less buggy than current version.

- Trello card:
https://trello.com/c/CddC46Kq/53-when-adding-a-new-patient-through-the-ui-replace-usage-of-fancy-auto-complete-text-input-for-coach-name-with-a-old-fashioned-sel

- proof of change:
![Screen Shot 2021-07-09 at 12 58 49](https://user-images.githubusercontent.com/13635035/125118855-e7f18680-e0b5-11eb-94f5-6d05101cb93d.png)

2021-07-09 18:57 UTC, rweald commented on package.json
> -    "typescript": "~3.7.2",
Let's now bump a pretty big version of typescript as part of another commit / PR. That is a big enough change it warrants it's own testing + PRs

2021-07-09 18:58 UTC, rweald commented on package.json
> +    "antd": "^4.16.6",
Why are we introducing a massive UI library dependency to fix a small bug in the coach dropdown? Seems like it could just be a vanilla HTML `input`, no?

2021-07-09 19:00 UTC, rweald requested changes
Shouldn't need to pull in a massive UI library, and all the associated architectural + dependency coupling just to move something to a select input. Since all the coaches use chrome anyway, the normal chrome form field for a select should be more than sufficient.

2021-07-09 19:03 UTC, g-vega-cl commented on package.json
> -    "typescript": "~3.7.2",
Perfect, I'll separate it into it's own PR.

2021-07-09 19:04 UTC, g-vega-cl commented on package.json
> +    "antd": "^4.16.6",
Yes, Actually. I'll just use the vanilla input and avoid updating TS for this bug.

2021-07-09 19:04 UTC, rweald commented on package.json
> +    "antd": "^4.16.6",
👍

2021-07-09 19:05 UTC, rweald commented on package.json
> -    "typescript": "~3.7.2",
Yeah ideally we can just totally avoid dealing with a TS update right now. Unless there is a very specific security issue we need to address. 

Seems like we have much higher priorities that warrant our time more than this.

2021-07-13 17:29 UTC, rweald requested changes

2021-07-13 17:29 UTC, rweald commented on src/components/AddPatientForm.tsx
> +    const getCoachesDropdown = () => {
Let's use async/await here rather than promise chaining.

2021-07-13 17:29 UTC, rweald commented on src/components/AddPatientForm.tsx
> +                const newCoachId = coachDropdown.filter((coach: any) => {
would be nice to avoid the addition of new `any` types here if possible. Always good to try and be explicit about the type / shape of the data.

2021-07-13 17:29 UTC, rweald commented on src/components/AddPatientForm.tsx
> +              {coachDropdown.map((coach: any, index: any) => (
Same as above around not using `any`. You especially should not be using any for the `index` param, which should be typed correctly automatically.

2021-07-13 17:45 UTC, rweald approved these changes

2021-07-13 17:46 UTC, merged