Appointments/show in patient page
coachmehealth/sms-care-portal-front-end pull request #37
Opened 2021-08-05 20:43 UTC by g-vega-cl

purpose:
 - Show upcoming patient appointments in a table in patient's dashboard.

Trello:
- https://trello.com/c/aqqEQwet/80-appointments-coaches-can-see-a-table-with-all-their-upcoming-appointments-sorted-soonest-to-not-soon

2021-08-05 21:20 UTC, rweald requested changes

2021-08-05 21:20 UTC, rweald commented on src/api/patientApi.ts
> +  { accessToken }: { accessToken: string }
I'm not a big fan of us having to pass around the access token for these extra requests. 

Would be much nicer if we had a way to make requests that automatically included the access token.

2021-08-05 21:20 UTC, rweald commented on src/api/patientApi.ts
> +  return new Promise((resolve, reject) => {
Let's use async/await rather than then/catch form here.

2021-08-05 21:20 UTC, rweald commented on src/api/patientApi.ts
> +        for (let i = 0; i < res.data.length; i++) {
I see what you were going for here, but this is definitely not the way we want to be adding length onto appointments 😂 . We should either have the server own the data an pass it along as part of the JSON payload, or we should make it a purely view related concern that we model as some fixed constant upstream of this raw data. 

Transforming the data on the client to include a different field that's hard coded is definitely going to cause confusion and future bugs.

2021-08-05 21:20 UTC, rweald commented on src/components/AppointmentForm.tsx
> +    const newAppointment = await secureAxios.post("/api/appointments/", {
Given that we own the client + server, we know the request to get the list of appointment is going to be very quick and light weight. 

I don't think it's worth all this extra client complexity to try and model the changes state on the client. 

When the new appointment is added, just re-hit the GET endpoint to update the list of appointments. Way way less likely to be buggy, and a ton less complexity for us to maintain.

2021-08-05 21:20 UTC, rweald commented on src/components/PaitentAppointmentTable.tsx
> +            <tr key={index}>
If the `appointment` record already has an `_id` you could save yourself the trouble of using the index and just have `key={appointment._id}` just a bit less code to maintain and reason about.

2021-08-05 21:20 UTC, rweald commented on src/components/AppointmentForm.tsx
> +import PatientAppointmentTable from "./PaitentAppointmentTable";
I don't think this is the right file name for this new display code to go. You are are lacking a higher level parent component that should be responsible for controlling both the form to add new components, and the logic to render the existing components. 

Something like: 

```
const PatientAppointmentsSection = () => {
  const appointments = Some Logic to fetch appointments from server
  return (
    <SomeContainer>
      <AppointmentForm />
      {appointments && <AppointmentTable appointments={appointments} />}
    </SomeContainer>
  )
};

```

2021-08-05 21:20 UTC, rweald commented on src/pages/PatientRecords.tsx
> +  const { data: appointments, isLoading: loadingAppointments } = useQuery(
It goes along with the earlier comment, but I really don't think we want this 1 particular component owning fetching all the possible data that will populate this page. 

If we decompose this page down into sub-components that are responsible for a dedicated "section" + it's associated data, we have a much more robust page setup that is more immune to random bugs, and generally much much easier to maintain.

2021-08-06 16:11 UTC, g-vega-cl commented on src/components/AppointmentForm.tsx
> +    const newAppointment = await secureAxios.post("/api/appointments/", {
I moved this to it's own folder, so it might be annoying to find this fix.
I removed the appointments `useState` and instead used `refetch` from `react-query`

2021-08-09 23:11 UTC, rweald approved these changes

2021-08-09 23:12 UTC, merged