Add eslint
coachmehealth/sms-care-portal-front-end pull request #4
Opened 2021-02-16 15:32 UTC by chrisoney

Unsure if this is the preferred configuration, but eslint should be good to go.

2021-02-19 17:46 UTC, rweald commented on package.json
> +    "lint": "eslint '*/**/*.{js,ts,tsx}' --quiet --fix",
This is a very common way to set things up, but I prefer having 2 tasks available, 1 that runs the linter to check for errors and doesn't change anything, and another that attempts to auto fix things. 

That way you have a task you can run to check code quality of PRs / branches without making the git tree dirty.

2021-02-19 17:46 UTC, rweald commented on .eslintrc.json
> +{
Probably makes sense to have consistency as much as possible between the BE and FE. Using the `.eslintrc` from the backend is probably a good starting point. Then we can extend it with the React one to help catch issues with hooks as well.

2021-02-19 22:24 UTC, rweald commented
I take back some of my suggestion about copying the backend since that is a node project and not react. 

This is the eslint config I use at work for a typescript + react app, and I quite like it. Not overly opinionated, but keeps a lot of things standardized 

```
module.exports = {
  root: true,
  extends: 'react-app',
  parser: '@typescript-eslint/parser',
  plugins: ['prettier', '@typescript-eslint'],
  rules: {
    'prettier/prettier': 'error',
  },
};
```

2021-02-19 23:04 UTC, rweald commented
Actually ignore my prior comment suggestion. Realized we can keep largely the same eslint setup between the front and backend by simply extends airbnb/base vs full airbnb.

2021-02-28 05:02 UTC, chrisoney commented
I think I've got it all set. Set up a secondary script to actually run the fix, while the first only checks for errors. The eslintrc file now matches the one from the backend, but with full airbnb. I was wondering if we should also separate the scripts in the backend package.json (and if I should do it in the same way).

2021-03-04 17:31 UTC, rweald commented
I'm less worried about having a long lived `lint-fix` task since ideally that only needs to be run on the whole codebase once. After the initial automated fix task, our editors should be able to lint the specific files we are working on upon save, and the if we do forget CI will notify us.

2021-03-04 17:37 UTC, rweald requested changes
When I checkout this branch, `yarn install` and then `npx eslint .` I am unable to run eslint because of some missing dependencies. Same error come up using your new `yarn lint` task. 

I'm guessing you might have some lingering libraries in node_modules, or cross project resolution which is giving it the false sense it can run on your box, but not on a fresh project install.

2021-03-04 17:37 UTC, rweald commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.15.1",
I think we might be missing a couple of dependencies? We probably want `eslint-config-airbnb-typescript` so that we can extend `airbnb-typescript` for proper typescript setup with airbnb, which can be a fit funky without the TS specific setup. 

We also probably need `eslint-config-prettier` and/or `eslint-plugin-prettier` since we want to extend prettier.

2021-03-04 21:25 UTC, rweald commented on package.json
> +    "eslint-plugin-react": "^7.22.0",
Think we still need `eslint-plugin-prettier` if we want the prettier rules as part of running eslint. I'm not seeing any prettier warnings/errors locally and I can't believe the projects is perfectly formatted already 😂

2021-03-04 21:43 UTC, chrisoney commented on package.json
> +    "eslint-plugin-react": "^7.22.0",
Oops, thought I had added that. I'll update shortly

2021-03-05 01:33 UTC, rweald commented
I'm still getting that typescript parser issue

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
```

Looks like maybe also still in config for some reason?

For things in the `build` directory after `yarn build` or `tsc` has been run. Might be worth adding a `.eslintignore` for anything in _build/_

2021-03-05 01:39 UTC, rweald commented
I also think it's totally fine if we just want to say F-it and only worry about linting things in `src/`. That's where the consistency really matters, and those are the only files we'll actually be touching on a consistent basis. Could be worth just putting `config/` and `build` into _eslintignore_ that way we can get a lot of the benefit of linting without spending too much more time on tooling for edge cases.

2021-03-05 03:57 UTC, chrisoney commented
Gotcha, I ran it again and noticed that I had missed adding `"scripts"` to the previously altered line in the `tsconfig.json` file. Any chance those are what you were seeing?
Then I threw `/build` in a new `.eslintignore`.
I'm good either way in regards to including these things in the linting or ignoring them.
I don't see any more of the typescript parser issue (and I actually used search too this time), so if it's still there I agree that I should just throw those folders in the `.eslintignore` file and focus on my other task.

2021-03-19 00:17 UTC, rweald commented
Wow cleaning up all these linter issues is going to be brutal. With the really restrictive AirBnb config there is over 600 errors. I wonder if we should loosen our requirements and use something like the standard create-react-app config to try and get the number of changes we need to make down?

2021-03-19 00:44 UTC, rweald commented
@chrisoney I built on top the stuff you started and moved away from Airbnb because it was causing so many issues with Typescript + React + their highly opinionated setup. https://github.com/coachmehealth/sms-care-portal-front-end/pull/6

With those changes we should be able to fix some prettier issues automatically, and then our linter will be "green" and happy to start ensuring we don't break anything when we make changes.

2021-03-19 16:28 UTC, rweald approved these changes

2021-03-19 16:28 UTC, merged